-- MySQL Script generated by MySQL Workbench
-- Thu Apr 11 01:05:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dafv2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dafv2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dafv2` DEFAULT CHARACTER SET utf8mb3 ;
USE `dafv2` ;

-- -----------------------------------------------------
-- Table `dafv2`.`blacklistedtoken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`blacklistedtoken` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(1000) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`regional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`regional` (
  `idRegional` TINYINT NOT NULL AUTO_INCREMENT,
  `regional` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(75) NULL DEFAULT NULL,
  PRIMARY KEY (`idRegional`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`zona` (
  `idzona` TINYINT NOT NULL AUTO_INCREMENT,
  `Nombre_zona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idzona`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`centro_formacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`centro_formacion` (
  `idcentro_formacion` INT NOT NULL AUTO_INCREMENT,
  `idRegional` TINYINT NOT NULL,
  `idzona` TINYINT NOT NULL,
  `centro_formacion` VARCHAR(100) NOT NULL,
  `dir_centro_formacion` VARCHAR(75) NOT NULL,
  `telefono_centrof` VARCHAR(20) NULL DEFAULT NULL,
  `email_centrof` VARCHAR(30) NULL DEFAULT NULL,
  `ordenador_gasto` VARCHAR(75) NOT NULL,
  `telefono_ordenadorg` VARCHAR(20) NULL DEFAULT NULL,
  `email_ordenadorg` VARCHAR(35) NULL DEFAULT NULL,
  PRIMARY KEY (`idcentro_formacion`),
  INDEX `fk_Centro_formacion_Regional1_idx` (`idRegional` ASC) ,
  INDEX `fk_Centro_formacion_zona1_idx` (`idzona` ASC),
  CONSTRAINT `fk_Centro_formacion_Regional1`
    FOREIGN KEY (`idRegional`)
    REFERENCES `dafv2`.`regional` (`idRegional`),
  CONSTRAINT `fk_Centro_formacion_zona1`
    FOREIGN KEY (`idzona`)
    REFERENCES `dafv2`.`zona` (`idzona`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`departamento` (
  `iddepartamento` TINYINT NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(75) NULL DEFAULT NULL,
  PRIMARY KEY (`iddepartamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`municipio` (
  `idmunicipio` TINYINT NOT NULL AUTO_INCREMENT,
  `iddepartamento` TINYINT NOT NULL,
  `municipio` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idmunicipio`),
  INDEX `fk_municipio_departamento1_idx` (`iddepartamento` ASC) ,
  CONSTRAINT `fk_municipio_departamento1`
    FOREIGN KEY (`iddepartamento`)
    REFERENCES `dafv2`.`departamento` (`iddepartamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`sede_formacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`sede_formacion` (
  `idsede_formacion` INT NOT NULL AUTO_INCREMENT,
  `idcentro_formacion` INT NOT NULL,
  `idmunicipio` TINYINT NOT NULL,
  `sede_formacion` VARCHAR(100) NOT NULL,
  `dir_sede_formacion` VARCHAR(75) NOT NULL,
  `telefono_sedef` VARCHAR(20) NULL DEFAULT NULL,
  `email_sedef` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idsede_formacion`),
  INDEX `fk_centro_formacion_municipio1_idx` (`idmunicipio` ASC),
  INDEX `fk_sede_formacion_Centro_formacion1_idx` (`idcentro_formacion` ASC) ,
  CONSTRAINT `fk_centro_formacion_municipio1`
    FOREIGN KEY (`idmunicipio`)
    REFERENCES `dafv2`.`municipio` (`idmunicipio`),
  CONSTRAINT `fk_sede_formacion_Centro_formacion1`
    FOREIGN KEY (`idcentro_formacion`)
    REFERENCES `dafv2`.`centro_formacion` (`idcentro_formacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`certificacion_centrof`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`certificacion_centrof` (
  `idcertificacion_centrof` INT NOT NULL AUTO_INCREMENT,
  `idcentro_formacion` INT NOT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idcertificacion_centrof`),
  INDEX `fk_certificacion_centrof_centro_formacion1_idx` (`idcentro_formacion` ASC),
  CONSTRAINT `fk_certificacion_centrof_centro_formacion1`
    FOREIGN KEY (`idcentro_formacion`)
    REFERENCES `dafv2`.`sede_formacion` (`idsede_formacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`empresa_vigilancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`empresa_vigilancia` (
  `idempresa_vigilancia` INT NOT NULL AUTO_INCREMENT,
  `nombre_empresav` VARCHAR(100) NOT NULL,
  `nit_empresa` VARCHAR(25) NOT NULL,
  `direccion_empresav` VARCHAR(75) NOT NULL,
  `telefono_empresav` VARCHAR(20) NULL DEFAULT NULL,
  `email_empresav` VARCHAR(45) NULL DEFAULT NULL,
  `representante_legal` VARCHAR(75) NULL DEFAULT NULL,
  `telefono_representantel` VARCHAR(20) NULL DEFAULT NULL,
  `email_representantel` VARCHAR(35) NULL DEFAULT NULL,
  `persona_contacto` VARCHAR(75) NULL DEFAULT NULL,
  `telefono_personac` VARCHAR(20) NULL DEFAULT NULL,
  `email_personac` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idempresa_vigilancia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`contrato_empresav`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`contrato_empresav` (
  `idContrato_empresav` INT NOT NULL AUTO_INCREMENT,
  `idempresa_vigilancia` INT NOT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idContrato_empresav`),
  INDEX `fk_Contrato_empresav_empresa_vigilancia1_idx` (`idempresa_vigilancia` ASC) ,
  CONSTRAINT `fk_Contrato_empresav_empresa_vigilancia1`
    FOREIGN KEY (`idempresa_vigilancia`)
    REFERENCES `dafv2`.`empresa_vigilancia` (`idempresa_vigilancia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`obligaciones_contratista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`obligaciones_contratista` (
  `idobligaciones_contratista` INT NOT NULL AUTO_INCREMENT,
  `obligacion_contratista` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idobligaciones_contratista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`obligaciones_contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`obligaciones_contrato` (
  `idobligaciones_contrato` INT NOT NULL AUTO_INCREMENT,
  `idContrato_empresav` INT NOT NULL,
  `idobligaciones_contratista` INT NOT NULL,
  PRIMARY KEY (`idobligaciones_contrato`),
  INDEX `fk_obligaciones_contrato_Contrato_empresav1_idx` (`idContrato_empresav` ASC),
  INDEX `fk_obligaciones_contrato_obligaciones_contratista1_idx` (`idobligaciones_contratista` ASC) ,
  CONSTRAINT `fk_obligaciones_contrato_Contrato_empresav1`
    FOREIGN KEY (`idContrato_empresav`)
    REFERENCES `dafv2`.`contrato_empresav` (`idContrato_empresav`),
  CONSTRAINT `fk_obligaciones_contrato_obligaciones_contratista1`
    FOREIGN KEY (`idobligaciones_contratista`)
    REFERENCES `dafv2`.`obligaciones_contratista` (`idobligaciones_contratista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`detalle_contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`detalle_contrato` (
  `iddetalle_contrato` INT NOT NULL AUTO_INCREMENT,
  `idcertificacion_centrof` INT NOT NULL,
  `idobligaciones_contrato` INT NOT NULL,
  `cumple` VARCHAR(2) NULL DEFAULT NULL COMMENT 'SI\\nNO\\nNA',
  PRIMARY KEY (`iddetalle_contrato`),
  INDEX `fk_detalle_contrato_certificacion_centrof1_idx` (`idcertificacion_centrof` ASC),
  INDEX `fk_detalle_contrato_obligaciones_contrato1_idx` (`idobligaciones_contrato` ASC),
  
  CONSTRAINT `fk_detalle_contrato_certificacion_centrof1`
    FOREIGN KEY (`idcertificacion_centrof`)
    REFERENCES `dafv2`.`certificacion_centrof` (`idcertificacion_centrof`),
    
  CONSTRAINT `fk_detalle_contrato_obligaciones_contrato1`
    FOREIGN KEY (`idobligaciones_contrato`)
    REFERENCES `dafv2`.`obligaciones_contrato` (`idobligaciones_contrato`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`modulo` (
  `idmodulo` TINYINT NOT NULL AUTO_INCREMENT,
  `id_modulo_padre` TINYINT NOT NULL,
  `modulo` VARCHAR(45) NOT NULL,
  `url_modulo` VARCHAR(100) NOT NULL,
  `icono` VARCHAR(45) NOT NULL,
  `orden` TINYINT NOT NULL,
  `hijos` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`idmodulo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`perfil` (
  `idperfil` TINYINT NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`moduloxperfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`moduloxperfil` (
  `idmodulo` TINYINT NOT NULL AUTO_INCREMENT,
  `idperfil` TINYINT NOT NULL,
  `permiso` VARCHAR(10) NULL DEFAULT NULL,
  INDEX `fk_moduloxperfil_modulo1_idx` (`idmodulo` ASC),
  INDEX `fk_moduloxperfil_perfil1_idx` (`idperfil` ASC),
  CONSTRAINT `fk_moduloxperfil_modulo1`
    FOREIGN KEY (`idmodulo`)
    REFERENCES `dafv2`.`modulo` (`idmodulo`),
  CONSTRAINT `fk_moduloxperfil_perfil1`
    FOREIGN KEY (`idperfil`)
    REFERENCES `dafv2`.`perfil` (`idperfil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`puestos_vigilancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`puestos_vigilancia` (
  `idpuesto_vigilancia` TINYINT NOT NULL AUTO_INCREMENT,
  `descripcion_puesto` VARCHAR(70) NOT NULL,
  `tarifa_puesto` DECIMAL(4,0) NOT NULL,
  `ays` DECIMAL(5,0) NULL DEFAULT NULL,
  `iva` DECIMAL(2,0) NULL DEFAULT NULL,
  `total` DECIMAL(5,0) NULL DEFAULT NULL,
  PRIMARY KEY (`idpuesto_vigilancia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`puestosvxcentrof`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`puestosvxcentrof` (
  `idpuestosvxcentrof` INT NOT NULL AUTO_INCREMENT,
  `idcentro_formacion` INT NOT NULL,
  `idempresa_vigilancia` INT NOT NULL,
  `idpuesto_vigilancia` TINYINT NOT NULL,
  `cantidad_puestov` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`idpuestosvxcentrof`),
  INDEX `fk_puestosvxcentrof_centro_formacion1_idx` (`idcentro_formacion` ASC),
  INDEX `fk_puestosvxcentrof_puestos_vigilancia1_idx` (`idpuesto_vigilancia` ASC),
  INDEX `fk_puestosvxcentrof_empresa_vigilancia1_idx` (`idempresa_vigilancia` ASC),
  CONSTRAINT `fk_puestosvxcentrof_centro_formacion1`
    FOREIGN KEY (`idcentro_formacion`)
    REFERENCES `dafv2`.`sede_formacion` (`idsede_formacion`),
  CONSTRAINT `fk_puestosvxcentrof_empresa_vigilancia1`
    FOREIGN KEY (`idempresa_vigilancia`)
    REFERENCES `dafv2`.`empresa_vigilancia` (`idempresa_vigilancia`),
  CONSTRAINT `fk_puestosvxcentrof_puestos_vigilancia1`
    FOREIGN KEY (`idpuesto_vigilancia`)
    REFERENCES `dafv2`.`puestos_vigilancia` (`idpuesto_vigilancia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`vigilancia_electronica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`vigilancia_electronica` (
  `idvigilancia_electronica` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(60) NOT NULL,
  `tarifa` DECIMAL(4,0) NOT NULL,
  `ays` DECIMAL(4,0) NULL DEFAULT NULL,
  `iva` DECIMAL(4,0) NULL DEFAULT NULL,
  `total` DECIMAL(4,0) NULL DEFAULT NULL,
  PRIMARY KEY (`idvigilancia_electronica`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`puntosvelectronica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`puntosvelectronica` (
  `idpuntosvelectronica` INT NOT NULL AUTO_INCREMENT,
  `idcentro_formacion` INT NOT NULL,
  `idempresa_vigilancia` INT NOT NULL,
  `idvigilancia_electronica` INT NOT NULL,
  `cantidad` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`idpuntosvelectronica`),
  INDEX `fk_puntosvelectronica_centro_formacion1_idx` (`idcentro_formacion` ASC),
  INDEX `fk_puntosvelectronica_vigilancia_electronica1_idx` (`idvigilancia_electronica` ASC),
  INDEX `fk_puntosvelectronica_empresa_vigilancia1_idx` (`idempresa_vigilancia` ASC),
  CONSTRAINT `fk_puntosvelectronica_centro_formacion1`
    FOREIGN KEY (`idcentro_formacion`)
    REFERENCES `dafv2`.`sede_formacion` (`idsede_formacion`),
  CONSTRAINT `fk_puntosvelectronica_empresa_vigilancia1`
    FOREIGN KEY (`idempresa_vigilancia`)
    REFERENCES `dafv2`.`empresa_vigilancia` (`idempresa_vigilancia`),
  CONSTRAINT `fk_puntosvelectronica_vigilancia_electronica1`
    FOREIGN KEY (`idvigilancia_electronica`)
    REFERENCES `dafv2`.`vigilancia_electronica` (`idvigilancia_electronica`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dafv2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dafv2`.`usuario` (
  `idUsuario` TINYINT NOT NULL AUTO_INCREMENT,
  `idperfil` TINYINT NOT NULL,
  `idcentro_formacion` INT NOT NULL,
  `identificacion` VARCHAR(30) NOT NULL,
  `nombre_usuario` VARCHAR(60) NOT NULL,
  `apellido_usuario` VARCHAR(60) NOT NULL,
  `telefono_usuario` VARCHAR(20) NOT NULL,
  `email_usuario` VARCHAR(65) NOT NULL,
  `password` VARCHAR(300) NOT NULL,
  `estado` VARCHAR(10) NULL DEFAULT NULL,
  `resetCode` VARCHAR(255) NULL DEFAULT NULL,
  `resetExpires` DATETIME NULL DEFAULT NULL,
  `blackListedTokenId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_perfil1_idx` (`idperfil` ASC) ,
  INDEX `fk_Usuario_Centro_formacion1_idx` (`idcentro_formacion` ASC) ,
  INDEX `blackListedTokenId` (`blackListedTokenId` ASC) ,
  CONSTRAINT `fk_Usuario_Centro_formacion1`
    FOREIGN KEY (`idcentro_formacion`)
    REFERENCES `dafv2`.`centro_formacion` (`idcentro_formacion`),
  CONSTRAINT `fk_Usuario_perfil1`
    FOREIGN KEY (`idperfil`)
    REFERENCES `dafv2`.`perfil` (`idperfil`),
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`blackListedTokenId`)
    REFERENCES `dafv2`.`blacklistedtoken` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
